config/routes.rb
Rc9::Application.routes.draw do
  resources :peeps do
    collection do
      get 'find_by_email'
    end
  end
  resources :users
  resource :account, :controller => "users"
  resource :print, :controller => "print" do
    member do
      get :attendees
      get :lanyards
    end
  end
  resource :user_session
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => "user_sessions#new"
end

app/models/peep.rb
class Peep < ActiveRecord::Base
  default_scope order: 'lower(last_name), first_name'
  scope :form_returned, where(form_returned: true)
  scope :form_outstanding, where(form_returned: false)
  scope :twitterless, where("twitter IS NULL OR twitter = ''")
  
  after_create :subscribe
  before_destroy :unsubscribe
  
  include Gravtastic
  gravtastic
  
  def full_name
    "#{first_name} #{last_name}"
  end
  
  def dietary_requirements?
    !dietary_requirements.blank?
  end
  
  def twitter?
    !twitter.blank?
  end
  
  def twitter_handle
    twitter? ? "@#{twitter}" : ''
  end
  
  def ticket_type
    vip? ? 'VIP' : 'Standard'
  end
  
  def self.emails_str(scope = :all)
    Peep.send(scope).map { |p| p.email }.join(', ')
  end
  
  def subscribe
    mailchimp.list_subscribe(rc9_list_id, email, { 'FNAME' => first_name, 'LNAME' => last_name }, 'text', false, true, false, false)
  end
  
  def unsubscribe
    mailchimp.list_unsubscribe(rc9_list_id, email)
  end

  # private
    def mailchimp
      Hominid::API.new(CONFIG['mailchimp_api_key'])
    end
    
    def rc9_list_id
      mailchimp.find_list_by_name(CONFIG['railscamp_9_list'])['id']
    end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  
  validates_presence_of :email
  validates_presence_of :password
  
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # configuration here, see documentation for sub modules of Authlogic::Session
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper :all
  helper_method :current_user_session, :current_user

  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end
  
    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.record
    end
  
    def require_user
      unless current_user
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_user_session_url
        return false
      end
    end

    def require_no_user
      if current_user
        store_location
        flash[:notice] = "You must be logged out to access this page"
        redirect_to account_url
        return false
      end
    end
  
    def store_location
      session[:return_to] = request.request_uri
    end
  
    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end
end

app/controllers/peeps_controller.rb
class PeepsController < ApplicationController
  before_filter :require_user
  
  # GET /peeps
  # GET /peeps.xml
  def index
    @peeps = Peep.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @peeps }
    end
  end

  # GET /peeps/1
  # GET /peeps/1.xml
  def show
    @peep = Peep.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @peep }
    end
  end

  # GET /peeps/new
  # GET /peeps/new.xml
  def new
    @peep = Peep.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @peep }
    end
  end

  # GET /peeps/1/edit
  def edit
    @peep = Peep.find(params[:id])
  end

  # POST /peeps
  # POST /peeps.xml
  def create
    @peep = Peep.new(params[:peep])

    respond_to do |format|
      if @peep.save
        format.html { redirect_to(@peep, :notice => 'Peep was successfully created.') }
        format.xml  { render :xml => @peep, :status => :created, :location => @peep }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @peep.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /peeps/1
  # PUT /peeps/1.xml
  def update
    @peep = Peep.find(params[:id])

    respond_to do |format|
      if @peep.update_attributes(params[:peep])
        format.html { redirect_to(@peep, :notice => 'Peep was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @peep.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /peeps/1
  # DELETE /peeps/1.xml
  def destroy
    @peep = Peep.find(params[:id])
    @peep.destroy

    respond_to do |format|
      format.html { redirect_to(peeps_url) }
      format.xml  { head :ok }
    end
  end
  
  # GET /peeps/find_by_email?email=joe@example.com
  # GET /peeps/find_by_email.xml?email=joe@example.com
  def find_by_email
    @peep = Peep.find_by_email(params[:email])
    
    respond_to do |format|
      if @peep
        format.html { render :action => "show"}
        format.xml { render :xml => @peep }
      else
        format.html { render :text => "No peep found for #{params[:email]}." }
        format.xml { render :xml => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<error>No peep found for #{params[:email]}.</error>" }
      end
    end
  end
end

app/controllers/print_controller.rb
class PrintController < ApplicationController
  before_filter :require_user
  
  def show
    
  end
  
  def attendees
    respond_to do |format|
      format.pdf do
        send_data AttendeeList.new.to_pdf, filename: 'attendees.pdf', type: 'application/pdf'
      end
    end
  end
  
  def lanyards
    respond_to do |format|
      format.pdf do
        send_data LanyardInserts.new.to_pdf, filename: 'lanyards.pdf', type: 'application/pdf'
      end
    end
  end
  
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy
  
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default peeps_url
    else
      render :action => :new
    end
  end
  
  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Account registered!"
      redirect_back_or_default account_url
    else
      render :action => :new
    end
  end

  def show
    @user = @current_user
  end

  def edit
    @user = @current_user
  end

  def update
    @user = @current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/peeps_helper.rb
module PeepsHelper
end

app/helpers/print_helper.rb
module PrintHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Camp 9 Peeps</title>
  <%= stylesheet_link_tag :all %>
  <%= formtastic_stylesheet_link_tag %>
  <link rel="stylesheet" href="/stylesheets/rc9peeps.css" type="text/css" media="screen, projection">
  <link rel="stylesheet" href="/stylesheets/blueprint/screen.css" type="text/css" media="screen, projection">
  <link rel="stylesheet" href="/stylesheets/blueprint/plugins/link-icons/screen.css" type="text/css" media="screen, projection">
  <link rel="stylesheet" href="/stylesheets/blueprint/print.css" type="text/css" media="print">
  <!--[if lt IE 8]>
    <link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection">
  <![endif]-->
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div class="container">
  	<div class="span-24">
  	  <%= link_to((image_tag "/images/header.gif"), peeps_url, class: "noicon" )  %>
  	  <%= render_navigation if @current_user %>
  	</div>
  	<div class="span-4">
  	</div>
  	<div class="span-16">
  		<%= yield %>
  	</div>
  	<div class="span-4 last">
      <p><%= link_to "Log out", logout_url, class: "noicon" if @current_user %></p>
  	</div>
	
  	<div class="span-24">
  	</div>
  </div>
</body>
</html>

app/views/peeps/_form.html.erb
<%= semantic_form_for(@peep) do |f| %>
  <%= f.inputs %>
  
  <% if @peep.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@peep.errors.count, "error") %> prohibited this peep from being saved:</h2>

      <ul>
      <% @peep.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/peeps/edit.html.erb
<h1>Editing <%= @peep.full_name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @peep %> |
<%= link_to 'Back', peeps_path %>

app/views/peeps/index.html.erb
<h1>Listing <%= Peep.count %> Peeps</h1>

<p><%= Peep.form_returned.count %> forms returned so far.</p>

<table>
  <tr>
    <th>Name</th>
    <th>Twitter</th>
    <th>Email</th>
    <th>Form returned</th>
    <th>Ticket type<th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @peeps.each do |peep| %>
  <tr>
    <td><%= peep.full_name %></td>
    <td>
      <% unless peep.twitter.blank?%>
        <a href="http://twitter.com/<%= peep.twitter %>">@<%= peep.twitter %></a>
      <% end %>
    </td>
    <td><a href="mailto:<%= peep.email %>"><%= peep.email %></td>
    <td><%= peep.form_returned? ? "yes" : "" %></td>
    <td><%= peep.ticket_type %></td>
    <td><%= link_to 'Show', peep %></td>
    <td><%= link_to 'Edit', edit_peep_path(peep) %></td>
    <td><%= link_to 'Destroy', peep, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Peep', new_peep_path %>

app/views/peeps/new.html.erb
<h1>New peep</h1>

<%= render 'form' %>

<%= link_to 'Back', peeps_path %>

app/views/peeps/show.html.erb
<h1><%= @peep.full_name %></h1>
<p id="notice"><%= notice %></p>

<%= image_tag @peep.gravatar_url %>
<p><a href="mailto:<%= @peep.email %>"><%= @peep.email %></a></p>
<% if @peep.twitter? %>
  <p><a href="http://twitter.com/<%= @peep.twitter %>">@<%= @peep.twitter %></a></p>
<% end %>
<% if @peep.dietary_requirements? %>
  <p>Dietary requirements: <%= @peep.dietary_requirements %></p>
<% else %>
  <p>No special dietary requirements.</p>
<% end %>
<p>Has <%= "not " unless @peep.form_returned %>returned form.</p>
<%= link_to 'Edit', edit_peep_path(@peep) %> |
<%= link_to 'Back', peeps_path %>

app/views/print/show.html.erb
<h1>Print Stuff for Rails Camp 9</h1>

<p>Print <%= link_to "Attendees List", attendees_print_path(:pdf) %></p>

<p>Print <%= link_to "Lanyard Inserts", lanyards_print_path(:pdf) %></p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<% form_for @user_session, :url => user_session_path do |f| %>
  <%= f.label :email %><br />
  <%= f.text_field :email %><br />
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <br />
  <%= f.check_box :remember_me %><%= f.label :remember_me %><br />
  <br />
  <%= f.submit "Login" %>
<% end %>

app/views/users/_form.erb
<%= form.label :email %><br />
<%= form.text_field :email %><br />
<br />
<%= form.label :password, form.object.new_record? ? nil : "Change password" %><br />
<%= form.password_field :password %><br />
<br />
<%= form.label :password_confirmation %>

app/views/users/edit.html.erb
<h1>Edit My Account</h1>

<% form_for @user, :url => account_path do |f| %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Update" %>
<% end %>

<br /><%= link_to "My Profile", account_path %>

app/views/users/new.html.erb
<h1>Register</h1>

<% form_for @user, :url => account_path do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Register" %>
<% end %

app/views/users/show.html.erb
<h1>Profile</h1>
<p>
  <b>Email:</b>
  <%=h @user.email %>
</p>


<%= link_to 'Edit', edit_account_path %>